name: parcial_final
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  firebase_messaging: ^14.7.19
  flutter:
    sdk: flutter
  flutter_login: ^5.0.0
  flutter_secure_storage: ^9.2.2
  get: ^4.6.6
  http: ^1.2.0
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
