name: frontend_eventapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  http: ^1.2.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.0
  shared_preferences: ^2.2.3
  image_picker: ^0.8.4+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - google_fonts/
