// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbxtNACQOy--CLibfiTS_MnEbKrbR3xHQ',
    appId: '1:1047080107778:web:76a5a09b1656fed3550c1b',
    messagingSenderId: '1047080107778',
    projectId: 'spring-notipush',
    authDomain: 'spring-notipush.firebaseapp.com',
    storageBucket: 'spring-notipush.appspot.com',
    measurementId: 'G-VGQ9HQ9X1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2crMp1ZDncwLgQjaDAN-h3gsw6YTbZqs',
    appId: '1:1047080107778:android:6d26b3637f0f36c2550c1b',
    messagingSenderId: '1047080107778',
    projectId: 'spring-notipush',
    storageBucket: 'spring-notipush.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCwWtsnAjCNs6uWAbghqvl3MEi9SnaV7A',
    appId: '1:1047080107778:ios:efe9f060600cdf65550c1b',
    messagingSenderId: '1047080107778',
    projectId: 'spring-notipush',
    storageBucket: 'spring-notipush.appspot.com',
    iosBundleId: 'com.example.parcialFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCwWtsnAjCNs6uWAbghqvl3MEi9SnaV7A',
    appId: '1:1047080107778:ios:efe9f060600cdf65550c1b',
    messagingSenderId: '1047080107778',
    projectId: 'spring-notipush',
    storageBucket: 'spring-notipush.appspot.com',
    iosBundleId: 'com.example.parcialFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbxtNACQOy--CLibfiTS_MnEbKrbR3xHQ',
    appId: '1:1047080107778:web:f506eb63364f1296550c1b',
    messagingSenderId: '1047080107778',
    projectId: 'spring-notipush',
    authDomain: 'spring-notipush.firebaseapp.com',
    storageBucket: 'spring-notipush.appspot.com',
    measurementId: 'G-4NJYVCKL7E',
  );
}
